### ISSUE TITLE
Turn down the default for --p-reads-per-batch

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#130]
**Improvement Description**
We should turn down the default for `--p-reads-per-batch` to be more like 1000.

**Current Behavior**
Current default is 20000, which easily causes a MemoryError with 16GB of memory.

**Proposed Behavior**
If we set default to 1000 then we could freely recommend that users use higher values for `--p-n-jobs`.

**Comments**
1.Perhaps try a few different values for `--p-reads-per-batch`, at least 10000 and 5000.

**Comment by nbokulich** [comment]
right now the default=0 so that autoscaling is used (rpb = number of query sequences / n_jobs)

I am not sure we want to switch that off... we added autoscaling to address earlier issues that folks were having with parallel jobs.

One option is to separate autoscaling as its own param, distinct from reads per batch. Then rpb can be set to whatever one likes, and if autoscaling is True, rpb = rpb / jobs.

**Comment by BenKaehler** [comment]
Oh snap, sorry, I should have checked.

Ok, the problem was that I had a large dataset. Perhaps we should change the rule to

rpb = max(20000, number of query sequences / n_jobs)

**Comment by nbokulich** [comment]
sounds good. we should also talk about this parameter more in the tutorials — recommend something like rpb=1000 for SILVA (since that will work on a 16GB laptop)
