### ISSUE TITLE
Make sure pipeline isn't being sent over the wire more than necessary in the classifier

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#20]

**Comment by BenKaehler** [comment]
Perhaps remove parallelisation from `classify` in anticipation of the framework catering for parallelism?

**Comment by jairideout** [comment]
I think the code can be left as-is since we won't have parallelism support in the framework as soon as we thought. Once there's parallelism in the framework, I don't think the code will necessarily need to change in this plugin, because we'll be using `dask.distributed` under the hood, which hooks into `joblib`. @ebolyen do I have that right?

**Comment by BenKaehler** [comment]
I'm closing this as premature optimisation.
