### ISSUE TITLE
Should q2-feature-classifier support paired-end reads?

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#39]
Hi @gregcaporaso,

Currently, `q2-feature-classifier` supports paired-end reads by providing an alternative workflow. That is, you must extract paired-end reads from the reference data set, train a classifier, then classify paired-end reads using the classifier. You can't classify single-end reads with a paired-end read classifier and vice versa.

@nbokulich tells me that paired-end reads will usually be converted into single-end reads before they get to `q2-feature-classifier`.

So, should we remove support for paired-end reads from q2-feature-classifier?

Pros: reduce user confusion, reduce source complexity, reduce work.
Cons: if the paired-end reads don't overlap, you have to concatenate or discard reads.

We would expect that the current approach is better than concatenating or discarding reads, but we don't actually know.

Thanks!

**Comment by gregcaporaso** [comment]
@BenKaehler, have you benchmarked the method to see if it does better than classifying single-end reads? If so, and we have good docs for how to use it, we should keep it in. If you haven't really tested, or don't have/plan to document any time soon, I think we should drop it to reduce user confusion. Since it's part of the commit history, we can always revive it if we want to.

**Comment by BenKaehler** [comment]
Thanks @gregcaporaso, I'll take it out.
