### ISSUE TITLE
extract-reads should be split into two methods

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-feature-classifier#43]
`extract-reads` currently takes a ``method`` parameter with the possible values being `position` and `match`. When the value is `position`, the input type needs to be `FeatureData[AlignedSequence]`, and when the value is `match`, the input type needs to be `FeatureData[Sequence]`. This would make sense as two methods, one for each value of ``method``/input semantic type, and will save users from incorrectly using this method. (@BenKaehler and I both fell into the trap of using the incorrect input type, so it's very likely that others will as well.)

**Comment by gregcaporaso** [comment]
@BenKaehler, will you be able to work on this in the first few weeks of January? We're starting to plan for the release that we'll do during the week of 6 Feb. We'd want to have the changes in by 25 Jan (including updates to the classifier training tutorial). If that doesn't seem doable, could you let us know ASAP and one of us will take care of it?

**Comment by BenKaehler** [comment]
Hi @gregcaporaso, I've already done it on the dev fork. I'll have a chat to you at some point to figure out whether it's ok to just PR the dev fork. I'll need a PR on 'q2-types' too.

**Comment by gregcaporaso** [comment]
Sounds good - let me know if you need anything (e.g., help with a review).

**Comment by BenKaehler** [comment]
Just to update on this one. I'm going to drop both of the existing methods and only provide one that works on unaligned sequences. It will be configurable via parameters to give the same result as the current `extract_reads_by_match` method but will usually provide a fuzzy match based on percentage identity after local alignment. After some testing of the `extract_reads_by_position` method I'm dropping it because it gave highly variable read lengths even in small samples and because aligning reference databases turned out to be a problem.
