### ISSUE TITLE
review docstrings

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/q2-feature-classifier#46]
**Bug Description**
For example, `extract_reads` incorrectly mentions `readlength` and `classify` does not have a docstring.

**Comment by lkursell** [comment]
Will this issue extended to writing a description of all of the parameters available in the `fit-classifier-naive-bayes`?

**Comment by BenKaehler** [comment]
Thanks @lkursell, it may, or it may provide better information on how to decode what `--p-feat-ext--analyzer` means. The parameter names are derived automatically from [`scikit-learn`](http://scikit-learn.org/stable/) object parameters. In this case `analyzer` refers to the same parameter from the [`scikit-learn` text feature extraction hashing vectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.HashingVectorizer.html), as do all of the parameters prefixed with `feat-ext`. The `classify` parameters are from the [naïve Bayes classifier](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html), also in `scikit-learn`.

**Comment by thermokarst** [comment]
Hi @BenKaehler! It looks like this issue might no longer be necessary, since `classify` is no longer a method (and the replacements all have docstrings), and I wasn't able to find a reference to `readlength` in `extract_reads`. Feel free to close if that is the case, otherwise, can you update the issue to indicate why it should remain open? Thanks!
