### ISSUE TITLE
add confidence for all levels

### ISSUE THREAD

**Issue by johnchase** [qiime2/q2-feature-classifier#66]
**Improvement Description**
We may be interested in looking at multiple confidence levels quickly, this would allow the filtering to the confidence threshold on the fly rather than having to assign taxonomy for each threshold of interest

**Comments**
It could be useful to calculate the confidence for each taxonomy level.

**Comment by BenKaehler** [comment]
Thanks @johnchase.

This would certainly be technically possible.

Alternatively the work could all be done internally, so that you input an array of confidence thresholds and receive a set of assignments. I am not sure how this would best be accomplished within the QIIME2 framework.

I think it probably depends on what is downstream in the pipeline.

@gregcaporaso, @jairideout, would this be a good feature? What would be the best approach?

Thanks!

**Comment by nbokulich** [comment]
@BenKaehler would it increase runtime if confidence is calculated at multiple levels?

This would turn classification into a 3-step process (train, classify, trim) — because the implication is that full taxonomy strings would need to be provided in the output along with multi-level confidences. A separate step would need to be performed to trim at any confidence level except for 0, except for @BenKaehler 's suggestion of inputting an array of confidence levels to output.

The classifier runtime is fairly quick right now once the classifier is trained — so running the classifier multiple times at different confidence thresholds is not a major burden. Unless if we expect that multi-level confidence would benefit most users, the potential runtime increases and additional step to classification would be detrimental to most use cases. 

@johnchase could you provide a little more detail about your use case? Is this something most users would use most of the time?

**Comment by BenKaehler** [comment]
Thanks @nbokulich, calculating multiple assignments for different confidence levels would take not much more time than doing it for one confidence level.

Without knowing @johnchase's use case, this feature would make a big difference if you wanted to try 1000 confidence levels but not much difference if you wanted to try 10.

**Comment by johnchase** [comment]
@BenKaehler The way I was thinking about this is that the user would not pass a list of confidence levels of interest, rather all of the confidence levels would be calculated and the the user could determine whatever cutoff they were interested in.

The output then could be two tables, one that was the consensus taxonomy at each level for each  feature, and one that was the confidence level of each taxonomy level for each feature.

An example output could be:
```python
        1              2              3          4           5         6 
seq1    Planctomycetes Planctomycetia Gemmatales Gemmataceae SomeGenus SomeSpecies	

        1   2    3  4   5   6 
seq1    1.0 1.0 1.0 0.7 0.5 0.2
```

Then if we want to filter to a confidence of 0.51 it would be very fast to create a mask out of the confidence table and apply it to the taxa table and not have to reassign taxonomy

**Comment by BenKaehler** [comment]
Thanks @johnchase, it sounds like you want to implement a slider, or similar?

So this would require some new data types etc. I will now await to the wisdom of @gregcaporaso, @jairideout, and @nbokulich.

**Comment by nbokulich** [comment]
@johnchase sounds like you are talking about BLAST or vsearch consensus classifiers, not the naive-bayes classifier. Is this correct?

If you are talking about consensus classifiers, one big issue with your suggestion is that you might not have consensus > 50% at any given level. Which taxonomic affiliation do you list in such a case? The most common? What if there's a tie?

Your use case is still not 100% clear to me — could you please clarify? Are you benchmarking on some sort of test data?

**Comment by johnchase** [comment]
Yes I was referring to the consensus classifier.  The use case is that there may be times when we want to look at the 51% consensus, others the 90%, or 70% or 60% and it would be preferable to not reassign taxonomy to our to our entire database ~200,000 DSVs each time we want to look at a difference consensus percent, when the taxonomy has already been assigned.

> What if there's a tie?

That's a good question maybe it would be better to have an option where the taxonomy is calculated to the 51% confidence, but the score is provided for each level?

**Comment by gregcaporaso** [comment]
I'm going to close this as there hasn't been activity in several years, but feel free to re-open if there is still interest in this.
