### ISSUE TITLE
Should classify-sklearn error when "dummy" jobs are created?

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-feature-classifier#90]
When running `classify-sklearn`, it's up to the user to do the load-balancing per job such that the parallelism works as best as possible. As such when running `N` (N > 1) parallel jobs, there might be situations where the number of reads to be processed is smaller than the number of reads that each job can process, and as such all reads are processed by one job, still all other `N-1` jobs are created (note that each job will require some space to allocate the pre-trained classifier, which can be a lot for big databases like Silva). This gives the untrained eye the impression that parallelism is or isn't working.

An easy solution would to check before the classification starts, and produce an error with a proposed solution. An alternative would be to not create the `N-1` jobs that will do nothing (though this would probably be prone to misinterpretations).

**Comment by jairideout** [comment]
This sounds like a useful optimization, thanks for reporting it @ElDeveloper!

**Comment by BenKaehler** [comment]
Having mulled it over, this is sadly not an easy solution, because the inputs are streamed, so the master has no way of knowing how many reads it will see before classification starts.

It could perhaps warn if this situation has occurred after execution, but for a long-running job this is less than ideal.

It would be nice if it could run an `grep -c '^>'` on the `.fasta` before it gets started. @jairideout, would there be an easy way to do that?

**Comment by jairideout** [comment]
Sure! You could use a `subprocess` call to `grep` or `ag` (`ag` can be orders of magnitude faster than `grep`). There's recipes out there for `grep` clones written in Python, which are more cross-platform compatible than a `grep` subprocess (some use `mmap`, others `regex`, etc.). All of these strategies would need to be benchmarked on real sequence data to determine what'll be the fastest for this particular application.

Since conda has `grep` and `ag` packages, a `subprocess` call would probably be the quickest way to get this going, and it'd be as cross-platform compatible as the rest of the qiime2 ecosystem.

Note that `grep` or `ag` will still take a full linear pass through the file, so the performance hit may not be worth it, especially considering that this parallelism is supposed to speed up the process :)

**Comment by BenKaehler** [comment]
Thanks @jairideout. Sorry, I didn't make my question particularly clear. I probably wouldn't use `grep`, I just meant is there a way to do an initial pass through the file to count the reads without parsing the fasta and holding it in memory? Currently I get this input as a `DNAIterator`. How do I find the file that that it came from?

I'm thinking that we could include an option for `reads_per_batch` (the new name for `chunk_size`) like `auto`, so the process could optionally take the performance hit of doing a pass through the file first. Note that this performance hit should be negligible:
```
$ time grep -c '^>' 99_otus.fasta 
203452

real	0m0.343s
user	0m0.273s
sys	0m0.060s
```

**Comment by ebolyen** [comment]
@BenKaehler, you should be able to ask for a different view (`DNAFASTAFormat` iirc), that object will be "pathlike", it has a `.path` attribute if you like the new Python 3 pathlib stuff, or you can just cast as a string (`str(my_view)`) to get a normal path.
